### PR TITLE
Implement verify new member email process with Mailgun

### PR DESCRIPTION
**Pull request by highskillmasters-admin**
The details are in https://github.com/highskillmasters/highskillmasters-api/issues/6.

### CODE REVIEW

**Review by mhaidarhanif — COMMENTED** [review]
Tried on development. Should be tried on production. Staging is better, but we have to setup first.

**Review by mhaidarhanif — COMMENTED** [review]
For now, let's approve and merge. Keep in mind to update the fetch URL on frontend too.

**Review by mhaidarhanif — COMMENTED** [review]
Wait, just to be safe. Let's keep the deprecated API on. Should already using middleware here so different routes can use the same process.

**Review by mhaidarhanif — COMMENTED** [review]
Looks safer now! 👍

**Review by mhaidarhanif — APPROVED** [review]
Approve multiple members routes and middlewares.

**Comment by highskillmasters-admin** [comment]
@mhaidarh Remember to setup the `.env`!

**Pull request merged**
