### PR TITLE
Setup basic tests with Jest and GitHub Actions

### LINKED ISSUE #1: Implement tests
This project needs some tests. Please put the dependencies / softwares to include in the test environment.

- MongoDB
- Node.js
- ...

### LINKED ISSUE #10: Use CI to check if build is pass
Use CI to check if build is pass with GitHub Actions. Since this is an open source project.

### PR DESCRIPTION
**Pull request by rahmanfadhil**
PR for #1 

- Install Jest and Sinon
- Setup basic GitHub Actions
- Write tests for route controllers

### CODE REVIEW

**Comment by rahmanfadhil** [comment]
This setup doesn't even mongo tho 🤣

**Comment by mhaidarhanif** [comment]
@rahmanfadhil haha It's okay, I will review it soon.

**Comment by highskillmasters-admin** [comment]
@mhaidarh @rahmanfadhil We've updated a lot of breaking changes in the configuration. Might break the tests. Please check again too. Thanks

**Comment by highskillmasters-admin** [comment]
Should also update the ESLint config.

**Comment by highskillmasters-admin** [comment]
Merged and closed for now. Later on we'll fix the test suite issues. @mhaidarh @rahmanfadhil

**Pull request merged**
